const express = require("express");
const multer = require("multer");
const storageMulterAccounts = require("../../helpers/storageMulterAccounts");
const upload = multer({ storage: storageMulterAccounts() });
const router = express.Router();
const controller = require("../../controllers/admin/my-account.controller.js");
router.get("/", controller.index);
router.get("/edit", controller.edit);
router.patch("/edit", upload.single("avatar"), controller.editPatch);
module.exports = router;
